# Generated by Django 5.0.6 on 2024-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betterself", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="section",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="workout",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
