# Generated by Django 5.0.6 on 2024-06-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betterself", "0002_alter_exercise_id_alter_section_id_alter_workout_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="betterself.section",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="betterself.workout",
            ),
        ),
    ]
